DROP SCHEMA IF EXISTS league_insults;

CREATE SCHEMA leauge_insults;
USE leauge_insults;

CREATE TABLE Ahri (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Akshan (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Amumu (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Bard (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Blitzcrank (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Braum (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Briar (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE ChoGath (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Draven (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Fizz (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Garen (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Gwen (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Heimerdinger (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Illaoi (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Ivern (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Jax (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Jhin (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Kassadin (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Katarina (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Kled (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE KogMaw (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE KSante (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Lux (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Malzahar (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE MasterYi (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Morgana (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Nasus (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE NunuWillump (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Pantheon (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Rammus (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Rengar (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Shaco (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Singed (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Teemo (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Trundle (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Tryndamere (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Twitch (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Warwick (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Yasuo (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Yone (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Yuumi (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);

CREATE TABLE Zed (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);
