USE leauge_insults;

INSERT INTO Ahri (content) VALUES ('UwU'), ('Fuchsschwanz Buttplug ist bestellt. :wink:');
INSERT INTO Akshan (content) VALUES ('Halbe Bibel in der W-Beschreibung, ganzer Huhrensohn.'), ('Versuch dich mal davon wiederzubeleben, was dir in der Hölle passiert.');
INSERT INTO Amumu (content) VALUES ('Haha, Emo!'), ('Der Champ ist wie ein IRL-Cosplay für dich.');
INSERT INTO Bard (content) VALUES ('Du bist also das komische Kind... .'), ('Auch eine Art zu sagen, dass du deine Freunde hasst.');
INSERT INTO Blitzcrank (content) VALUES ('Niemand mag dich.'), ('Gottes Strafe wird dich treffen wie deine Hooks (also vermutlich gar nicht).');
INSERT INTO Braum (content) VALUES ('Du bist cool.'), ('Gigachad.'), ('Da GOAT!');
INSERT INTO Briar (content) VALUES ('Fußfetisch confirmed.'), ('#FeetLover69'), ('Das Outing als Fußfetischist:in.');
INSERT INTO ChoGath (content) VALUES ('Nom nom motherfucker!'), ('Raw :wink:');
INSERT INTO Draven (content) VALUES ('Rassist:in.'), ('Schieb dir deine Axt in den Arsch.'), ('Dein Schnauzer ist länger als dein Schwanz.');
INSERT INTO Fizz (content) VALUES ('Auf dieser Welt gibt es Wölfe und Schafe... . Aber du... du bist ein richtiger FISCH.'), ('Erstick an deinem Plastik.');
INSERT INTO Garen (content) VALUES ('Muss ja auch für die geistig umnachteten Menschen Möglichkeiten geben, dieses Spiel zu spielen.'), ('Demacia in deinen Arsch.'), ('Demacia? Wohl eher Dementia.');
INSERT INTO Gwen (content) VALUES ('Mögest du dich mit deiner Schere kastrieren.'), ('Schnipp, schnapp, Pimmel ab!');
INSERT INTO Heimerdinger (content) VALUES ('https://twitter.com/BADASSDATABASE/status/1748816590651482137'), ('https://pbs.twimg.com/media/GEULavFWMAAitcb?format=png&name=small');
INSERT INTO Illaoi (content) VALUES ('Irgendwas mit Tentakeln halt. Schon komisch, das zu spielen... .'), ('Interessante Art, sich als Heantai-Lover zu outen.');
INSERT INTO Ivern (content) VALUES ('Der komische im Freundeskreis also... .'), ('Fucking Gutmensch... .'), ('Nein, Homöopathie funktioniert nicht, Patrick.');
INSERT INTO Jax (content) VALUES ('Heute schon ein Kind angefasst?'), ('Darfst du überhaupt noch in die Nähe von Kindergärten?'), ('Wo ist deine Einladung zur Epstein-Iland?'), ('Na, rennst wieder kleinen Mädchen hinterher?');
INSERT INTO Jhin (content) VALUES ('Psychopath... .'), ('Vier... vier Schüsse in deine Wirbelsäule.');
INSERT INTO Kassadin (content) VALUES ('Hätte dein Vater dich gegen den Ofen gewichst, hättest du nur einmal gestunken.'), ('Gestern ist Gestern, Morgen ist Morgen, deine rassistischen Tendenzen bleiben unverborgen.'), ('Kein Wunder, dass dein Vater dich vor Level 16 verlassen hat.');
INSERT INTO Katarina (content) VALUES ('Einfach nein.'), ('Man soll Menschen ja nicht für ADHS beleidigen, ABER ...'), ('Nicht nur deine Haare zeigen, dass du keine Seele hast.');
INSERT INTO Kled (content) VALUES ('Furry exposed.'), ('Ein kleiner Nachwuchsrassit :pleading_face:');
INSERT INTO KogMaw (content) VALUES ('Ekelhaft.'), ('Besteht überhaput ein Unterschied zwischen dem Champ und dir IRL?');
INSERT INTO KSante (content) VALUES ('Die Würde des Menschen ist unantastbar, ABER ...'), ('Ob Tank oder Bruiser, dich hat niemand lieb.');
INSERT INTO Lux (content) VALUES ('UwU Kawaii, für wie viele Skins hast du deinen Körper schon verkauft?'), ('Dein Champ hat mehr Skins, als du Sozialkontakte IRL.');
INSERT INTO Malzahar (content) VALUES ('Du bist der Krebs, der von deiner E verbreitet wird.');
INSERT INTO MasterYi (content) VALUES ('Steht dir das Arschwasser schon bis zu den Knöcheln? ~Der coolste Gockel'), ('Verschwinde einfach in deiner Q.'), ('Heute schon Q gedrückt?');
INSERT INTO Morgana (content) VALUES ('3 Sekunden können auch kurz sein, wenn sie der Rest deines Lebens sind... . Und jetzt renn!'), ('Rooted in Mamas Keller wie deine Q.');
INSERT INTO Nasus (content) VALUES ('DU HUND!'), ('Furry exposed.'), ('Bonk.');
INSERT INTO NunuWillump (content) VALUES ('https://twitter.com/BADASSDATABASE/status/1749068550965227623'), ('https://pbs.twimg.com/media/GEXwRfYXgAA30eg?format=png&name=medium');
INSERT INTO Pantheon (content) VALUES ('Baguette.'), ('Gibst du auf?');
INSERT INTO Rammus (content) VALUES ('Ok.'), ('Okay.'), ('OK!');
INSERT INTO Rengar (content) VALUES ('Pussy.'), ('Insgeheim Discord Kitten.');
INSERT INTO Shaco (content) VALUES ('Du dummer Huhrensohn.'), ('Deine Q cosplayed deine Eltern nach deiner Geburt.');
INSERT INTO Singed (content) VALUES ('Ja keine Ahnung, bist halt das komische Kind... .'), ('Ruf an: 01806 313031');
INSERT INTO Teemo (content) VALUES ('Du Ratte.'), ('Auf dich spucken sogar die frankfurter Kanalratten aus dem Bahnhofsviertel.'), ('Schade, dass dein Dad sich seit Jahren in deiner Passiven befindet.');
INSERT INTO Trundle (content) VALUES ('Zumindest der IQ stimmt überein.'), ('Das Design passt zu deinem Charakter.');
INSERT INTO Tryndamere (content) VALUES ('AAAAAHHHHHHHH!'), ('AAAAAAAAAAAch du Scheiße... .');
INSERT INTO Twitch (content) VALUES ('Du kleine, wertlose Kanalratte.'), ('Ein Statement zu deiner politischen Gesinnung?');
INSERT INTO Warwick (content) VALUES ('Deine Q oder Ult wird deinen emotionalen Schaden nicht heilen.'), ('Verändert durch chemische Drogen? Das kennst du doch irgendwoher ... .');
INSERT INTO Yasuo (content) VALUES ('Geh IRL auf deinen Powerspike.'), ('Dein Bruder ist eh nützlicher.'), ('Kritischer Pick.'), ('F and dein Team.');
INSERT INTO Yone (content) VALUES ('Quasi der Pick für Yasuo-Spieler, denen es zu peinlich geworden ist.'), ('Viel Spaß, die nächsten 15 Minuten deiner Lebenszeit zu verschwenden.');
INSERT INTO Yuumi (content) VALUES ('NEIN! VERPISS DICH, EHRLICH, LASS ES EINFACH'), ('WARUM???'), ('Hiermit wurdest du von der Gesellschaft ausgeschlossen.'), ('Viel Spaß beim kochen.');
INSERT INTO Zed (content) VALUES ('Nein, du bist nicht Faker.'), ('Wie dein Schatten, ist dein Vater auch kurz nach Erzeugung verschwunden.'), ('LOOK AT THE QSS, LOOK AT THE MOVES, HE DIED AGAIN!'), ('Wenn du es für dich selber brauchst, dann ist es wohl so ... .')